version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  config-from-consul:
    image: config-from-consul
    ports:
      - "6363"
    environment:
      WAZO_CONSUL_HOST: consul
      WAZO_CONSUL_PORT: 8500
      WAZO_CONSUL_SCHEME: http
      WAZO_CONSUL_SERVICE: config-from-consul

  myservice:
    image: myservice

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  consul:
    image: consul:1.0.7
    ports:
      - "8500"

  thread-exception:
    image: thread-exception
    volumes:
      - ../..:/usr/local/src/xivo-lib-python:ro
